import { Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Header from "@/components/header";
import Footer from "@/components/footer";

import "./globals.css";
import { getUser } from "@/_data/user";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Peach Flask",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await getUser();

  return (
    <html lang="en">
      <body className={`${poppins.className} bg-[#fff2ea]`}>
        <Header user={user} />
        <Toaster position="top-center" reverseOrder={false} />
        <main className="min-h-[92dvh]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
